# Site settings
title: "Luis Zelaya"
email: tu.email@ejemplo.com
description: >-
  Un blog personal enfocado en programación, donde comparto tips, tutoriales y buenas prácticas sobre desarrollo web y tecnología.
baseurl: "" # subpath of your site, e.g. /blog
url: "https://tudominio.com" # base hostname & protocol
github_username: CodingWithLuis
youtube_username: '@codewithluis'

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Luis Zelaya"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
